# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from decart_oasis._proto import a2v_pb2 as a2v__pb2


class A2VServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Initialize = channel.unary_unary(
                '/decart.inference.a2v.A2VService/Initialize',
                request_serializer=a2v__pb2.InitializeRequest.SerializeToString,
                response_deserializer=a2v__pb2.InitializeResponse.FromString,
                )
        self.Prompt = channel.unary_unary(
                '/decart.inference.a2v.A2VService/Prompt',
                request_serializer=a2v__pb2.PromptRequest.SerializeToString,
                response_deserializer=a2v__pb2.PromptResponse.FromString,
                )
        self.Infer = channel.unary_unary(
                '/decart.inference.a2v.A2VService/Infer',
                request_serializer=a2v__pb2.InferRequest.SerializeToString,
                response_deserializer=a2v__pb2.InferResponse.FromString,
                )
        self.Finish = channel.unary_unary(
                '/decart.inference.a2v.A2VService/Finish',
                request_serializer=a2v__pb2.FinishRequest.SerializeToString,
                response_deserializer=a2v__pb2.FinishResponse.FromString,
                )


class A2VServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Initialize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Infer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Finish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_A2VServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=a2v__pb2.InitializeRequest.FromString,
                    response_serializer=a2v__pb2.InitializeResponse.SerializeToString,
            ),
            'Prompt': grpc.unary_unary_rpc_method_handler(
                    servicer.Prompt,
                    request_deserializer=a2v__pb2.PromptRequest.FromString,
                    response_serializer=a2v__pb2.PromptResponse.SerializeToString,
            ),
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=a2v__pb2.InferRequest.FromString,
                    response_serializer=a2v__pb2.InferResponse.SerializeToString,
            ),
            'Finish': grpc.unary_unary_rpc_method_handler(
                    servicer.Finish,
                    request_deserializer=a2v__pb2.FinishRequest.FromString,
                    response_serializer=a2v__pb2.FinishResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'decart.inference.a2v.A2VService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class A2VService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/decart.inference.a2v.A2VService/Initialize',
            a2v__pb2.InitializeRequest.SerializeToString,
            a2v__pb2.InitializeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Prompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/decart.inference.a2v.A2VService/Prompt',
            a2v__pb2.PromptRequest.SerializeToString,
            a2v__pb2.PromptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/decart.inference.a2v.A2VService/Infer',
            a2v__pb2.InferRequest.SerializeToString,
            a2v__pb2.InferResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Finish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/decart.inference.a2v.A2VService/Finish',
            a2v__pb2.FinishRequest.SerializeToString,
            a2v__pb2.FinishResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
