# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x17\x64\x65\x63\x61rt.inference.common\"\xb8\x01\n\x05\x45rror\x12\x30\n\x04\x63ode\x18\x01 \x01(\x0e\x32\".decart.inference.common.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\x12<\n\x07\x64\x65tails\x18\x03 \x03(\x0b\x32+.decart.inference.common.Error.DetailsEntry\x1a.\n\x0c\x44\x65tailsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\xcd\x02\n\tErrorCode\x12\x1a\n\x16\x45RROR_CODE_UNSPECIFIED\x10\x00\x12\x1e\n\x1a\x45RROR_CODE_INVALID_SESSION\x10\x01\x12\x1f\n\x1b\x45RROR_CODE_ALREADY_FINISHED\x10\x02\x12\x1e\n\x1a\x45RROR_CODE_INVALID_REQUEST\x10\x03\x12\x1c\n\x18\x45RROR_CODE_INVALID_MODEL\x10\x04\x12\x1d\n\x19\x45RROR_CODE_INVALID_FORMAT\x10\x05\x12#\n\x1f\x45RROR_CODE_INVALID_ENVIRONMENTS\x10\x06\x12\x19\n\x15\x45RROR_CODE_PROMPT_SET\x10\x07\x12&\n\"ERROR_CODE_UNSUPPORTED_SDK_VERSION\x10\x08\x12\x1e\n\x1a\x45RROR_CODE_INVALID_API_KEY\x10\t*\xa2\x01\n\x0b\x46rameFormat\x12\x1c\n\x18\x46RAME_FORMAT_UNSPECIFIED\x10\x00\x12\x15\n\x11\x46RAME_FORMAT_JPEG\x10\x01\x12\x15\n\x11\x46RAME_FORMAT_H264\x10\x02\x12\x14\n\x10\x46RAME_FORMAT_VP9\x10\x03\x12\x14\n\x10\x46RAME_FORMAT_VP8\x10\x04\x12\x1b\n\x17\x46RAME_FORMAT_RAW_YUV420\x10\x05\x42(Z&github.com/decart/api/inference/commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/decart/api/inference/common'
  _globals['_ERROR_DETAILSENTRY']._options = None
  _globals['_ERROR_DETAILSENTRY']._serialized_options = b'8\001'
  _globals['_ERRORCODE']._serialized_start=229
  _globals['_ERRORCODE']._serialized_end=562
  _globals['_FRAMEFORMAT']._serialized_start=565
  _globals['_FRAMEFORMAT']._serialized_end=727
  _globals['_ERROR']._serialized_start=42
  _globals['_ERROR']._serialized_end=226
  _globals['_ERROR_DETAILSENTRY']._serialized_start=180
  _globals['_ERROR_DETAILSENTRY']._serialized_end=226
# @@protoc_insertion_point(module_scope)
